[build]
  # No build command needed for backend-only deployment
  command = "echo 'No build step required for serverless functions'"
  # Use a simple public directory that we'll create
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8889

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
